name: Update README Activity Log

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 核心步驟：執行 activity-log action
      - uses: TheDanniCraft/activity-log@latest
        with:
          # 使用我們在步驟 B 儲存的 Secret
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

          # [重要] 這裡要填入你的 GitHub 用戶名
          USERNAME: 'AweiLu'

          # 要更新的檔案
          TARGET_FILE: 'README.md'

          # (可選) 顯示活動的最大數量
          MAX_LINES: 10

          # [重要] 作業要求的 placeholder
          START_PLACEHOLDER: ''
          END_PLACEHOLDER: ''
